---
- name: Install Java 17 OpenJDK
  become: true
  package:
    name: java-17-openjdk
    state: present

- name: Install Apache Maven
  become: true
  package:
    name: maven
    state: present

- name: Set JAVA_HOME environment variable
  become: true
  lineinfile:
    dest: /etc/environment
    state: present
    line: "JAVA_HOME=/etc/alternatives/java_sdk"
